<?php use App\Model\Topic;$this->headTitle('Event'); ?>
<div class="container-fluid defaultbox">
    <h3 class="text-center"><?= $this->escapeHtml($this->name); ?></h3>
    <h5 class="text-center"><?= $this->escapeHtml($this->description); ?></h5>
    <p class="text-small text-justify">
        <?= $this->escapeHtml($this->eventText); ?>
    </p>
    <div class="text-end text-xx-small text-white-50">Event erstellt am <?= $this->createTime->format('j.m.Y-G:i'); ?> Uhr</div>
</div>
<div class="container-fluid defaultbox">
    <div class="row">
        <div class="col">Start</div>
        <div class="col text-smaller"><?= $this->startTime->format('j.m.Y-G:i'); ?> Uhr</div>
    </div>
    <div class="row">
        <div class="col">Laufzeit</div>
        <div class="col text-smaller"><?= $this->duration; ?> Tage</div>
    </div>
    <div class="row">
        <div class="col">Ende</div>
        <div class="col text-smaller"><?= $this->endTime->format('j.m.Y-G:i'); ?> Uhr</div>
    </div>
    <div class="row">
        <div class="col">Aktiv</div>
        <div class="col text-smaller"><?= $this->isActive ? 'Ja' : 'Nein'; ?></div>
    </div>
</div>

<?php if ($this->isLoggedIn): ?>
    <?php if (!$this->isParticipant($this->loggedInUser, $this->participants)): ?>
        <div class="container-fluid">
            <a href="/event/participant/subscribe/<?= $this->id; ?>">Für das Event anmelden</a>
        </div>
    <?php else: ?>
        <div class="container-fluid">
            <a href="/event/participant/unsubscribe/<?= $this->id; ?>">Vom Event abmelden</a>
        </div>
<div class="container-md"></div>
        <?php
        /** @var Topic $topic */
        foreach ($this->topics as $topic): ?>

            <div class="row d-flex justify-content-center align-items-center">
                <div class="col"><?= $topic->getTopic(); ?></div>
                <div class="col"><?= $topic->getDescription(); ?></div>
            </div>
            <hr>
        <?php endforeach;?>
    </div>

    <?php endif ?>
<?php endif ?>
<div class="container-fluid defaultbox">
    <div class="row">
        <div class="col-4">Teilnehmer</div>
        <div class="col-8">Projekt</div>
    </div>
    <?php
    foreach ($this->participants as $partipicant):
        ?>
        <div class="row text-small">
            <div class="col-4">
                <a href="/user/<?= $partipicant[App\Model\User::class]->getId() ?>"><?= $this->escapeHtml($partipicant[App\Model\User::class]->getName()) ?></a>
            </div>
            <div class="col-8">
                <?php if ($partipicant[App\Model\Project::class] instanceof App\Model\Project): ?>
                <a href="/project/<?= $partipicant[App\Model\Project::class]->getId() ?>"><?= $this->escapeHtml(
                        $partipicant[App\Model\Project::class]->getTitle()
                    ) ?></a>
                <?php endif; ?>
            </div>
        </div>
    <?php
    endforeach;
    ?>

</div>
