<?php $this->headTitle('Event');
?>

<div class="container-fluid">
    <ul>
        <li>Name: <?= $this->name ?></li>
        <li>Kurzbeschreibung: <?= $this->description ?></li>
        <li>Beschreibung: <?= $this->eventText ?></li>
        <li>Erstellt am: <?= $this->createTime ?></li>
        <li>Start am: <?= $this->startTime ?></li>
        <li>Laufzeit: <?= $this->duration ?></li>
        <li>Endet am: <?= $this->endTime ?></li>
        <li>Aktiv: <?= $this->active ?></li>
        <li>Erstellt von: <a href="/user/<?= $this->eventUserId ?>"> <?= $this->eventUser ?></a></li>
        <div class="container">
            <div class="row">
                <div class="col">
                    Teilnehmer
                </div>
                <div class="col">
                    Projekt
                </div>
            </div>
            <?php
                foreach ($this->participants as $partipicant):
            ?>
            <div class="row">
                <div class="col">
                    <a href="/user/<?= $partipicant[\App\Model\User::class]->getId() ?>"><?= $partipicant[\App\Model\User::class]->getName() ?></a>
                </div>
                <div class="col">
                    <a href="/project/<?= $partipicant[\App\Model\Project::class]->getId() ?>"><?= $partipicant[\App\Model\Project::class]->getTitle() ?></a>
                </div>
            </div>
            <?php
                endforeach;
            ?>
        </div>
    </ul>
</div>
