<ul class="navbar-nav d-flex">
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <span class="fas fa-user-cog"></span><span> </span>
        </a>
        <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDropdown">
            <li class="text-center fw-bolder"><?= $this->escapeHtml($this->userName) ?></li>
            <li><a class="dropdown-item" href="/logout">Abmelden</a></li>
        </ul>
    </li>
</ul>