<?php

declare(strict_types=1);

return static function (Mezzio\Application $app): void {
    $app->get(
        '/testmail',
        [
            App\Handler\TestMailHandler::class,
        ],
        App\Handler\TestMailHandler::class
    );
    $app->get(
        '/api/me[/]',
        [
            Authentication\Handler\ApiMeHandler::class,
        ],
        Authentication\Handler\ApiMeHandler::class
    );
    $app->get(
        '/api/csrf[/]',
        [
            App\Handler\CsrfTokenHandler::class,
        ],
        App\Handler\CsrfTokenHandler::class,
    );
    $app->get(
        '/',
        [
            App\Handler\IndexHandler::class,
        ],
        App\Handler\IndexHandler::class
    );
    $app->get(
        '/event[/]',
        [
            App\Middleware\Event\EventListMiddleware::class,
            App\Handler\EventListHandler::class,
        ],
        App\Handler\EventListHandler::class
    );
    $app->post(
        '/event[/]',
        [
            Authentication\Middleware\IsLoginAuthenticationMiddleware::class,
            App\Middleware\Event\EventCreateValidationMiddleware::class,
            App\Middleware\Event\EventCreateMiddleware::class,
            App\Handler\EventCreateHandler::class,
        ],
        App\Handler\EventCreateHandler::class
    );
    $app->get(
        '/event/{eventId:\d+}[/]',
        [
            App\Middleware\Event\EventMiddleware::class,
            App\Handler\EventHandler::class,
        ],
        App\Handler\EventHandler::class
    );
    $app->get(
        '/event/{eventName}[/]',
        [
            App\Middleware\Event\EventNameMiddleware::class,
            App\Handler\EventNameHandler::class,
        ],
        App\Handler\EventNameHandler::class
    );
    $app->put(
        '/event/participant/subscribe/{eventId:\d+}[/]',
        [
            Authentication\Middleware\IsLoginAuthenticationMiddleware::class,
            App\Middleware\Event\EventParticipantSubscribeMiddleware::class,
            App\Handler\EventParticipantSubscribeHandler::class,
        ],
        App\Handler\EventParticipantSubscribeHandler::class
    );
    $app->put(
        '/event/participant/unsubscribe/{eventId:\d+}[/]',
        [
            Authentication\Middleware\IsLoginAuthenticationMiddleware::class,
            App\Middleware\Event\EventParticipantUnsubscribeMiddleware::class,
            App\Handler\EventParticipantUnsubscribeHandler::class,
        ],
        App\Handler\EventParticipantUnsubscribeHandler::class
    );
    $app->post(
        '/user/register[/]',
        [
            Authentication\Middleware\UserRegisterValidationMiddleware::class,
            Authentication\Middleware\UserRegisterMiddleware::class,
            Authentication\Handler\UserRegisterSubmitHandler::class,
        ],
        Authentication\Handler\UserRegisterSubmitHandler::class
    );
    $app->get(
        '/user/{userUuid}[/]',
        [
            Authentication\Middleware\IsLoginAuthenticationMiddleware::class,
            App\Middleware\UserMiddleware::class,
            App\Handler\UserHandler::class,
        ],
        App\Handler\UserHandler::class
    );
    $app->get(
        '/login[/]',
        [
            Authentication\Handler\LoginHandler::class,
        ],
        Authentication\Handler\LoginHandler::class
    );
    $app->post(
        '/login[/]',
        [
            Authentication\Middleware\LoginValidationMiddleware::class,
            Authentication\Middleware\LoginAuthenticationMiddleware::class,
            Authentication\Handler\LoginHandler::class,
        ],
        Authentication\Middleware\LoginAuthenticationMiddleware::class
    );
    $app->get(
        '/logout[/]',
        [

            Authentication\Handler\LogoutHandler::class,
        ],
        Authentication\Handler\LogoutHandler::class
    );
};
