<?php declare(strict_types=1);

return static function (Mezzio\Application $app): void {
    $app->get(
        '/',
        [
            App\Handler\IndexHandler::class,
        ],
        App\Handler\IndexHandler::class
    );
    $app->get(
        '/event[/]',
        [
            App\Handler\EventAboutHandler::class,
        ],
        App\Handler\EventAboutHandler::class
    );
    $app->get(
        '/event/{eventId:\d+}[/]',
        [
            App\Middleware\EventMiddleware::class,
            App\Middleware\EventUserMiddleware::class,
            App\Handler\EventHandler::class,
        ],
        App\Handler\EventHandler::class
    );
    $app->get(
        '/event/list[/]',
        [
            App\Middleware\EventListMiddleware::class,
            App\Handler\EventListHandler::class,
        ],
        App\Handler\EventListHandler::class
    );

    $app->get(
        '/user/{userId:\d+}[/]',
        [
            App\Middleware\UserMiddleware::class,
            App\Handler\UserHandler::class,
        ],
        App\Handler\UserHandler::class
    );

    $app->get(
        '/login',
        [
            Mezzio\Flash\FlashMessageMiddleware::class,
            Authentication\Handler\LoginHandler::class,
        ],
        Authentication\Handler\LoginHandler::class
    );
    $app->post(
        '/login',
        [
            Mezzio\Flash\FlashMessageMiddleware::class,
            Authentication\Middleware\LoginAuthenticationMiddleware::class,
            Authentication\Handler\LoginHandler::class,
        ],
        Authentication\Middleware\LoginAuthenticationMiddleware::class
    );

    $app->get(
        '/logout',
        [
            Mezzio\Flash\FlashMessageMiddleware::class,
            Authentication\Handler\LogoutHandler::class,
        ],
        Authentication\Handler\LogoutHandler::class
    );

    $app->get(
        '/api/ping',
        [
            App\Handler\PingHandler::class,
        ],
        App\Handler\PingHandler::class
    );
};
