name: Development Deployment
on:
  push:
    branches: [ "master" ]
jobs:
  deployment_of_hackathon_to_build:
    env:
      VUE_APP_API_BASE_URL: 'https://build.hackathon.exdrals.de'
    runs-on: ubuntu-20.04
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 19
        uses: actions/setup-node@v2
        with:
          node-version: '19'

      - name: Install Composer Dependencies
        run: composer install

      - name: Run create openapi Data
        run: composer run-script openapi

      - name: FTP Deploy to Development Server (Staging)
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.BUILD_HOST }}
          username: ${{ secrets.BUILD_USER }}
          password: ${{ secrets.BUILD_PASSWORD }}
          state-name: ".ftp-deploy-sync-state-backend.json"
          exclude: |
            **/.git*
            **/*.dist
            **/*.dist/**
            **/.git*/**
            **/bin/**
            **/tests/**
            **/config/autoload/**
            **/config/migrations/**
            **/node_modules/**
            **/client/**
            **/database/**
            **/scripts/**
            **/tests/**
            **/docker/**
            **/public/assets/**
            **/public/index.html
