name: Development Deployment
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-dev

      - name: npm install
        run: npm install

      - name: npm run build
        run: npm run build

      - name: FTP Deploy to Development Server (Staging)
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.BUILD_HOST }}
          username: ${{ secrets.BUILD_USER }}
          password: ${{ secrets.BUILD_PASSWORD }}
          exclude: |
            **/.git*
            **/*.dist
            **/*.dist/**
            **/.git*/**
            **/bin/**
            **/config/migrations/**
            **/node_modules/**
            **/build/**
            **/database/**
