name: Development Deployment
on:
  push:
    branches: [ "master" ]
jobs:
  deployment_of_hackathon_to_build:
    env: VUE_APP_API_BASE_URL = https://build.hackathon.exdrals.de
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 19
        uses: actions/setup-node@v2
        with:
          node-version: '19'

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-dev

      - name: Run create openapi Data
        run: composer run-script openapi

      - name: npm install
        working-directory: ./client
        run: npm install

      - name: npm run build
        working-directory: ./client
        run: npm run build

      - name: FTP Deploy to Development Server (Staging)
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.BUILD_HOST }}
          username: ${{ secrets.BUILD_USER }}
          password: ${{ secrets.BUILD_PASSWORD }}
          exclude: |
            **/.git*
            **/*.dist
            **/*.dist/**
            **/.git*/**
            **/bin/**
            **/tests/**
            **/config/autoload/**
            **/config/migrations/**
            **/node_modules/**
            **/client/**
            **/database/**
            **/scripts/**
            **/tests/**
            **/docker/**
