name: Development Deployment
on:
  push:
    branches: [ "master" ]

jobs:
  send_embed:
    runs-on: ubuntu-latest
    name: Send an embed to Discord

    steps:
    - name: Run the GitHub Actions Status Embed Action
      uses: SebastiaanZ/github-status-embed-for-discord@main
      with:
        # Discord webhook
        webhook_id: '1234567890'  # Has to be provided as a string
        webhook_token: ${{ secrets.webhook_token }}

        # Optional arguments for PR-related events
        # Note: There's no harm in including these lines for non-PR
        # events, as non-existing paths in objects will evaluate to
        # `null` silently and the github status embed action will
        # treat them as absent.
        pr_author_login: ${{ github.event.pull_request.user.login }}
        pr_number: ${{ github.event.pull_request.number }}
        pr_title: ${{ github.event.pull_request.title }}
        pr_source: ${{ github.event.pull_request.head.label }}

  phplint:
    name: PHP Lint
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHP Linter
        run: composer run-script phplint

  phpstan:
    name: PHP Stan
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHP Stan
        run: composer run-script phpstan

  phpcs:
    name: PHP CodeSniffer
    needs:
      - phplint
      - phpstan
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHP Codesniffer
        run: composer run-script phpcs

  phpunit:
    name: PHP Unit
    needs:
      - phplint
      - phpstan
      - phpcs
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHP Unit Test
        run: composer run-script test

  deployment_of_hackathon_to_build:
    name: Deploy Build
    needs:
      - phpcs
      - phplint
      - phpstan
      - phpunit
    env:
      VUE_APP_API_BASE_URL: 'https://build.hackathon.exdrals.de'
    runs-on: ubuntu-20.04
    steps:
      - name: Get latest code
        uses: actions/checkout@v4.1.1

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress --no-dev

      - name: Run create openapi Data
        run: composer run-script openapi

      - name: FTP Deploy to Development Server (Staging)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.BUILD_HOST }}
          username: ${{ secrets.BUILD_USER }}
          password: ${{ secrets.BUILD_PASSWORD }}
          state-name: ".ftp-deploy-sync-state-backend.json"
          exclude: |
            **/.git*
            **/*.dist
            **/*.dist/**
            **/.git*/**
            **/bin/**
            **/tests/**
            **/config/autoload/**
            **/config/migrations/**
            **/node_modules/**
            **/client/**
            **/database/**
            **/scripts/**
            **/tests/**
            **/docker/**
            **/public/assets/**
            **/public/index.html
            **/*.md
            **/*.xml
            **/*.neon
            **/composer.json
            **/*.yml
            **/*.lock
            **/LICENSE
