name: PHP Code Sniffer

on: pull_request

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP Code Sniffer
        run: |
          composer require --dev squizlabs/php_codesniffer

      - name: Check coding standards
        run: vendor/bin/phpcs
